### ISSUE TITLE
Logging with debug levels

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#512]
### Description
* The several components should have logging messages with logging levels for debug purposes.
* The `maestro` cli should have flags to activate debug.

### Tasks
- [x] Logging in `execution` pkg.
- [x] Logging in `gprc` pkg.
- [x] Logging in cli command with debug flag.
- [x] Simplify logging levels and remove zap dependency.
- [x] Replace mock.Logger with logs.Logger with debug.
