### ISSUE TITLE
Functions to get resources

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#559]
### Description
* Functions to get the several available resources.
* The functions should be able to filter by the fields.

### Tasks
- [ ] Function to get assets.
- [ ] Function to get orchestrations.
- [ ] Function to get stages.
- [ ] Function to get links.
