### ISSUE TITLE
grpc interfaces for execute package to handle messages

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#615]
### Description
* The `execute` pkg should not depend on the `invoke` pkg.
* There should be domain entities that define the behaviour of messages and method.
* The `invoke` pkg should implement these interfaces.

### Tasks
- [x] Define the domain interfaces for message and method.
- [x] Implement and test the `execute` pkg with the new interfaces.
- [x] Update the `invoke` pkg to implement the interfaces using grpc.
- [x] Remove old reflection code from codebase.
- [x] Refactor grpc services in tests to only use one proto file per test file.
