### ISSUE TITLE
Remove errdefs package

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#671]
### Description
* The `errdefs` package should be replaced by concrete errors with parameters that can be easily tested.
* The `errors` pkg from the `stdlib` should be used to distinguish errors.
* Tests to returned errors should use the `errors.Is` and the `errors.As` functions.

### Tasks
- [x] Replace `InvalidArgument` error for smaller more concrete errors.
- [x] Replace `FailedPrecondition` error for smaller more concrete errors.
- [x] Replace `Unavailable` error as it is unused.
- [x] Replace `Internal` error from similar error with descriptive message.
- [x] Remove `Unknown` error (all errors that were not defined by the above classes are unknown).
