### ISSUE TITLE
Create methods should already receive correct parameter types

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#673]
### Description
* Create methods should already receive the correct parameter types.
* Only logic to see if the necessary dependencies are met should be tested.
* Request classes will no longer be necessary.

### Task
* [x] Refactor `create.Asset` to receive `AssetName` and `OptionalImage`.
* [x] Refactor `create.Orchestration` to receive `OrchestrationName`.
* [x] Refactor `create.Stage` to receive `StageName`, `MethodContext` and `Orchestration`.
* [x] Refactor `create.Link` to receive `LinkName` and endpoints.
