### ISSUE TITLE
Execute orchestration

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#692]
### Description
The `execute` package should have:
* A way to create executions from orchestrations.
* The orchestration struct should be different from the api one as it should immediately contain all the necessary information to run the execution.
* The discovery of the methods should be totally agnostic to the build mechanism.
* A way to start and stop an execution.

### Tasks
- [x] Build an execution.
- [x] Start and stop an execution.
- [x] Test with a linear execution.
- [x] Test with a non-linear execution.
- [x] Remove old execution code.
- [x] Remove unused protobuf files for old test.
