### ISSUE TITLE
Extra validations to link creation

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#697]
### Description
The creation of links should verify more constraints that were previously verified the building the execution.

### Tasks
- [x] Verify if the target stage input already consumes the entire message.
- [x] Verify if the target stage input receives the same field twice.
- [x] Add unit tests with missing values.
