### ISSUE TITLE
Refactor tests as map of test name to values

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#701]
### Description
* Test tables should have the signature `map[string]struct{...}` where string is the name of the test.
* All the packages should be refactored to follow this structure.

### Tasks
- [x] Refactor `create` pkg.
- [x] Refactor `grpc` pkg.
- [x] Refactor `internal` pkg.
