### ISSUE TITLE
Use tests with go-cmp package and Diff?

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#702]
### Description
* Tests should only depend on the `go-cmp` and `testing` pkgs.
* They should use the Diff method to assert equality and print the result.

### Tasks
- [x] Refactor `create` pkg.
- [x] Refactor `execute` pkg.
- [x] Refactor `grpc` pkg.
- [x] Refactor `internal` pkg.
- [x] Remove `gotest.tools/v3` dependency.
