### ISSUE TITLE
Parsing of orchestration files.

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#717]
### Description
* Configuration files should define orchestrations, stages, links and assets.
* The configuration spec from the java orchestrator should be supported.
* The new simpler configuration should also be supported.
* A struct that abstracts both configurations should be available.

### Tasks
- [x] Implement the v1 configuration.
- [x] Test failure cases for v1 configuration.
- [x] Implement the v0 configuration for compatibility with https://github.com/DuarteMRAlves/Pipeline-Orchestrator.
- [x] Test failure cases for v0 configuration.
- [x] Convert v0 to v1 configuration.
- [x] Remove parsing files from old codebase.
- [x] Rename pkg to `yaml` and functions to Read/Write.
