### ISSUE TITLE
Integration tests for execution with grpc

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#726]
### Description
* `execute` pkg should be tested with the `grpc` pkg.
* The `.proto` files should be unique for each test and separated from `unit` tests.

### Tasks
- [x] Linear pipeline.
- [x] Split and Merge pipeline.
- [x] Integration tests should not assume messages are not discarded.
- [x] Add random delays to stages in integration tests.
