### ISSUE TITLE
Maestro command to run and convert configurations

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#736]
### Description
* Create a maestro command using `cobra`.
* The command should have a subcommand to execute an orchestration.
* The command should have a subcommand to convert config versions.
* The run command should have a docker image to execute an orchestration.

### Tasks
- [x] Create a root `maestro` command.
- [x] Create a subcommand `run` to run an orchestration.
- [x] Create a subcommand `convert` to convert from v0 to v1.
- [x] Create a docker image to execute the `maestro run` subcommand.
