### ISSUE TITLE
Discard message on input of very slow stages.

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#739]
### Description
* Inputs for very slow stages should be discarded.
* A watcher routine should discard drain full channels.

### Tasks
- [x] ~~Implement queue that discards elements when full.~~
- [x] ~~Replace channels in execution for the queues.~~
- [x] Implement a watcher routine to drain channels.
- [x] Add the watcher routine to the execution.
- [x] Test slow stage in linear pipeline.
- [x] Remove implemented queue.
