### ISSUE TITLE
Map based Saver and Loader interfaces.

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#753]
### Description
* Implement `Saver` and `Loader` interfaces to store orchestrations, stages, links and assets.
* The underlying storage should use maps.
* No concurrency or rollbacks guarantees are required.
* Later another storage option with these guarantees can be implemented.

### Tasks
- [x] Implement interfaces for orchestrations.
- [x] Implement interfaces for stages.
- [x] Implement interfaces for links.
- [x] Implement interfaces for assets.
