### ISSUE TITLE
Refactor errors for behaviour instead of types

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#763]
### Description
* Errors should be tested for behaviour instead of specific types in order to avoid dependencies.
* Behaviour should be tested with interfaces the errors can implement.
* Error types should be private inside their packages.

### Tasks
- [x] Refactor `IncompatibleMessageDescriptor` error.
- [x] Refactor `InvalidIdentifier` error.
- [x] Refactor `AlreadyExists` error.
- [x] Refactor `NotFoundError` error.
- [x] Refactor sentinel errors to be private.
- [x] Refactor error structs to be private.
- [x] ~~Create temporary interface for requests that can be retried.~~ (Not needed for now).
- [x] Create not found interface for request with not found errors.
