### ISSUE TITLE
Cycles Support

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#772]
### Description

The `maestro` tool should support cycles. The following issues should be addressed:
- How to start a cycle.
- How to deal with slow stages and loss of messages.
- How to configure cycles.

### Tasks

- [x] Add initial state to links specification.
- [x] Add initial state to compiled links.
- [x] Validate cycles and online executions in pipeline compilation.
- [x] Add initial state in execution.
- [x] Add yaml option to configure initial state.
- [x] Documentation for new link option.
