### ISSUE TITLE
Add Execution Modes to Orchestration

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#775]
### Description

* Orchestrations should be created with a specific Execution Mode.
* If the mode is not specified, then it should be inferred as an Offline execution.

### Tasks
- [x] Create `enum` with `ExecutionMode` as in the proposal.
- [x] Add the execution mode to the orchestration.
- [x] ~~Offer a constructor with options for the execution mode.~~ (to be done by #778, verify before closing)
