### ISSUE TITLE
Rename Orchestration to Pipeline and refactor struct methods.

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#778]
### Description

* Updates to pipelines require calling the new function and copying all atributes except the ones for the change, which is prone to errors.
* A new way to modify pipelines should be developed.
* Pipelines should not be modified in-place in order to allow for safe concurrent access.

### Tasks
- [x] Rename Orchestration to Pipeline.
- [x] Refactor NewPipeline function to receive required arguments and options for the optional arguments.
- [x] Create functions that receive a pipeline and a set of modifications and return a new modified pipeline.
- [x] Update documentation with Orchestration.
