### ISSUE TITLE
Create Pipeline with ExecutionMode

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#781]
### Description
* A pipeline should be created with an execution mode.
* The execution mode should be specified in the pipeline configuration.

### Tasks
- [x] Add ExecutionMode parameter to `create.Pipeline`.
- [x] Update ExecutionMode to disallow wrong values.
- [x] Add `execution_mode` option to yaml configurations.
