### ISSUE TITLE
Dagger for Local Development

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#796]
### Description

* Dagger is a tool to manage CI/CD workflows and can replace Makefile in executing CI/CD tasks.
* Dagger should be used in local development.
* Remote integration can be done with regular scripts and later integrated with dagger.

### Tasks
- [x] Setup dagger.
- [x] Create actions to compile proto files.
- [x] Create actions to test go code.
- [x] Create actions to build executables in `target` folder.
- [ ] Investigate experimental platform feature.
- [ ] Create actions to create docker images.
- [ ] Remove makefile dependencies.
