### ISSUE TITLE
Build offline and online execution

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#803]
### Description

* The `Builder` function should build stages according to execution mode.

### Tasks
- [x] Store common information for online and offline stages in a struct.
- [x] Create factories for online and offline stages. They should be generic on channel type.
- [x] Execution struct generic on channel type.
- [x] Update the build to use the appropriate factory.
