### ISSUE TITLE
Create execution from each mode

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#804]
### Description

* Create an execution for each mode type.
* In offline stages, the channel drainer should be deactivated. The offline execution does not need a channel drainer.

### Tasks
- [x] ~~Disable channel drainer in execution with offline mode.~~
- [x] Create an execution for each mode.
- [x] Integration testing with grpc services.
