### ISSUE TITLE
Remove logs dependencies in packages.

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#812]
### Description

* Some packages use the logs pkg to perform logging. This should be replaced by functions that receive interfaces.
* Some tests use the `logs` pkg to perform logging. This should be removed, a simple struct should implement the Logger interface and print to stdout to avoid any dependencies.

### Tasks
- [x] Remove logs dependency in `internal/execute` pkg.
- [x] ~~Remove logs dependency in `test/integreation/grpcexecute` pkg.~~
- [x] Remove logs dependency in `internal/storage` pkg.
