### ISSUE TITLE
Create specific message types instead of mock.Message

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#814]
### Description

* Current mock messages use interface{}, making them very difficult to handle.
* Specific messages and message descriptors should be created for each test.

### Tasks
- [x] Create messages for `execute/unary_test.go`.
- [x] Create messages for `execute/source_test.go`.
- [x] Create messages for `execute/merge_test.go`.
- [x] Create messages for `execute/split_test.go`.
- [x] Create messages for `execute/execution_test.go`.
