### ISSUE TITLE
Compile into augmented graph.

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#838]
### Description

* Compilation should output an augmented graph, with the auxiliary stages.
* Allows for a one-to-one mapping between stages and links in the compiled pipeline and execution.

### Tasks
- [x] Compile into augmented pipeline.
- [x] Build execution from augmented pipeline.
- [x] Store invocation information in all stages.
