### ISSUE TITLE
Simplify method discovery and execution

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#839]
### Description

* Address, Service, Method should be simplified.
* The client should be renamed to follow `net` package from the `stdlib`.

### Tasks

- [ ] Simplify Address into underlying string type.
- [ ] Simplify Service into underlying string type.
- [ ] Simplify Method into underlying string type.
- [ ] Rename UnaryMethod.ClientBuilder to Dial and return type to Connection.
