### ISSUE TITLE
Replace jhump package dependency for golang proto package

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#842]
### Description

* `jhump` package uses the deprecated `github.com/golang/protobuf/proto` library.
* It can be replaced by the new `google.golang.org/protobuf/proto` library.
* A wrapper should be implemented for dynamic messages.

### Tasks

- [x] Reflection stream wrapper to list services and find symbols.
- [x] Message instance and type implementation.
- [x] MethodDesc implementation.
- [x] Resolver struct that implements the `method.Resolver` interface for grpc.
- [x] Swap old `grpc` package for new implementation in the remaining code.
- [x] Remove `jhump` package from project dependencies.
