### ISSUE TITLE
Unify Spec and compile config into api

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#846]
### Description

* The `spec` package should be renamed to `api` for the server.
* The `compile` package should compile from the `api` definitions.

### Tasks

- [x] Rename `spec` to `api`.
- [x] The `compile` package should compile from `api`.
- [x] Remove `compile/config.go` file.
