### ISSUE TITLE
Bump dependencies for 0.1.3 release

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#848]
### Description
* Bump dependencies on the start of a new release.

### Tasks
- [x] Bump go version from 1.18.3 to 1.19.
- [x] Bump protobuf version from 3.19.4 to 21.5.
- [x] Update modules versions.
