### ISSUE TITLE
Replace descriptors that already exist instead of error

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#852]
### Description

* google's proto package does not allow to descriptors to be registered with the same name.
    * leads to no conflicts on types of specific messages.
    * is more restrictive on the accepted definitions.
* jhump's proto package skips over the descriptor.
    * is less restrictive on the accepted definitions.
    * if two different messages have the same name, may lead to an error in the verification of the pipeline.
* a mix is if two different messages have the same name and are equal, they are accepted, otherwise an error is raised.

This issue implements the jumps version for backwards compatibility. A better approach will be discussed in #854.

### Tasks
- [x] Implement descriptors registry to store descriptors. The store should follow the jhump behaviour for backwards compatibility.
- [x] Replace `protoregistry.Files` for `ProtoRegistry`.
- [x] Open issue for better behaviour on registry.
