### ISSUE TITLE
Link Buffer Size

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#859]
### Description

* The user should be able to specify a link buffer size.
* A default value should be provided.

### Tasks

- [x] Add buffer size to link structure.
- [x] Create link channel with allowed size.
- [x] Add buffer size to link configuration.
