### ISSUE TITLE
Immutable structs in compiled package

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#860]
### Description

* `compiled` package should adopt a functional approach as it is purely domain logic.
* The structures should be made immutable.
* The structures should use references.
* Arrays should not be returned. Instead visitor functions should be used.
* The `compiled.New` function should be pure and receive the available methods as parameters.

### Task

- [x] Immutable `compiled.Stage`.
- [x] Immutable `compiled.Link`.
- [x] Immutable `compiled.Pipeline`.
