### ISSUE TITLE
Remove online execution mode

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#862]
### Description

* The Online Execution Mode should be removed.
* Instead, pipelines should use lower buffer sizes for real-time behaviour

### Tasks

- [x] Remove code with execution mode.
- [x] Remove documentation for execution modes.
- [x] Remove offline from structs and methods.
