### ISSUE TITLE
Remove v0 yaml configuration

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#863]
### Description

* Version 0 should be removed as it does not support new features.

### Tasks

- [ ] Remove code for version 0.
- [ ] Rename version 1 code to only version.
- [ ] Remove documentation on yaml version 0.
