### ISSUE TITLE
Timeout for calling stages

### ISSUE THREAD

**Issue by DuarteMRAlves** [DuarteMRAlves/maestro#866]
### Description

* The timeout for when calling a given stages should be configurable.
* For stages depending on user input, there should be a method to disable timeout.

### Tasks

- [ ] Add a `timeout` field to the stage configuration.
- [ ] Call the stages with a given timeout.
- [ ] Create e2e test with a large timeout and a slower stage.
